### ISSUE TITLE
An Option to hide the Dock.

### ISSUE THREAD

**Issue by Weather-OS** [fin444/truely-maximized#4]
Is there a way to also hide dock(s) when maximizing a window (Other than the "Dodge Window" feature).

**Comment by fin444** [comment]
Looks like this is possible with kwin scripts, but decently complicated. Rather than implementing it in Truely Maximised I think it would be better to look into porting https://github.com/luisbocanegra/kwin-panel-auto-hide to Plasma 6. Why can't you use dodge windows?

**Comment by Weather-OS** [comment]
> Why can't you use dodge windows?

It kinda takes away the immersion in some scenarios.

**Comment by fin444** [comment]
I also preferred Windows Can Cover. However, looking at the options for coding something like this, it would take a lot of work to make something that isn't just a buggy mess. I don't plan to implement this.

If you or someone else would like to, I'd be happy to take a look at the PR.

**Comment by Weather-OS** [comment]
> If you or someone else would like to, I'd be happy to take a look at the PR.
I’ll see what I can do
