### ISSUE TITLE
Listener does not work.

### ISSUE THREAD

**Issue by Redoxahmii** [fin444/truely-maximized#5]
I am using this on Plasma 6 and the listeners to show the title bar when going to the top edge does not seem to be working for me.

https://github.com/fin444/truely-maximized/assets/13983258/f7c1f26e-42da-4ce9-bf8f-63d00eff0055

**Comment by fin444** [comment]
Do you have it enabled in your screen edge settings?

![image](https://github.com/fin444/truely-maximized/assets/24360839/2ced33ec-d72b-41bb-a277-4b8a6c29292d)

**Comment by Redoxahmii** [comment]
Thanks for the quick reply. I did not have that enabled from there.
